# Generated by Django 4.1.7 on 2023-06-24 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('land_size_rai', models.DecimalField(decimal_places=2, max_digits=10)),
                ('land_size_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('land_title', models.CharField(choices=[('CHANOTE', 'Chanote'), ('NOR_SOR_SAM', 'Nor Sor Sam')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('access', models.CharField(choices=[('CONCRETE_ROAD', 'Concrete Road'), ('DIRT_TRACK', 'Dirt Track'), ('OTHER', 'Other')], max_length=20)),
                ('water', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('electricity', models.CharField(choices=[('YES', 'Yes'), ('NEARBY', 'Nearby'), ('NO', 'No')], max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='land.area')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='land.area')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='land.property')),
            ],
        ),
    ]
