# Generated by Django 4.1.7 on 2023-06-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=2)),
                ('starting_point', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='land.agency'),
            preserve_default=False,
        ),
    ]
