# Generated by Django 4.1.7 on 2023-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_alter_property_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land_size_rai',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_size_sqm',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
