# Generated by Django 4.1.7 on 2023-06-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_alter_agency_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='price_thb',
        ),
    ]
