# Generated by Django 4.1.7 on 2023-06-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_rename_price_property_price_thb'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_eur',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='price_gbp',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='price_usd',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_thb',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
