# Generated by Django 4.1.7 on 2023-06-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_property_price_eur_property_price_gbp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='land_size_ngan',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_size_wah',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_size_rai',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
