# Generated by Django 4.1.7 on 2023-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0008_property_land_size_ngan_property_land_size_wah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land_size_ngan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_size_rai',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_size_wah',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
