# Generated by Django 4.1.7 on 2023-07-08 07:33

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0010_property_latitude_property_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='land_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='land.landtitle'),
        ),
    ]
