# Generated by Django 4.1.7 on 2023-07-08 11:47

from django.db import migrations, models
import land.models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0011_landtitle_alter_property_land_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(upload_to=land.models.property_image_upload_path),
        ),
    ]
