# Generated by Django 4.1.7 on 2023-07-09 06:30

from django.db import migrations, models
import land.models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0013_property_land_size_acres_property_land_size_sqf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to=land.models.property_image_upload_path),
        ),
    ]
