# Generated by Django 4.1.7 on 2023-07-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0014_alter_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='land.area'),
        ),
    ]
