# Generated by Django 4.1.7 on 2023-07-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0015_alter_image_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='area',
        ),
    ]
